# syntax=docker/dockerfile:experimental

FROM alpine

RUN apk add --no-cache openssh-client git

RUN mkdir -p -m 0600 ~/.ssh && ssh-keyscan github.com >> ~/.ssh/known_hosts

RUN --mount=type=ssh git clone git@github.com:enricoaquilina/MaxBot.git MaxBot
#RUN --mount=type=ssh git clone https://enricoaquilina:l9q5e7b922470106@github.com/enricoaquilina/MaxBot.git MaxBot
